#!/usr/bin/env python3
"""Summarize task-level reconstruction mismatch statistics for report 39.

This script is read-only with respect to model outputs and datasets. It uses
existing STReasoner-8B full ST-Test 6144 outputs and the strict node/window
reconstruction evidence generated by find_bad_cases.py.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path
from statistics import mean, median
from typing import Any

_SCRIPT_DIR = Path(__file__).resolve().parent
_DEFAULT_ROOT = _SCRIPT_DIR.parents[2]
sys.path.insert(0, str(_SCRIPT_DIR))
sys.path.insert(0, str(_DEFAULT_ROOT))

from evaluation.evaluate_qa import _normalize_choice, _parse_series, load_prediction_files

import find_bad_cases
from find_bad_cases import (
    ST_TEST,
    configure_paths,
    exp_dir,
    extract_numeric_reconstructions,
    generated_path,
    load_jsonl,
)

TASKS = ["forecasting", "correlation", "entity", "etiological"]
CHOICE_TASKS = ["correlation", "entity", "etiological"]
TASK_LABEL = {
    "forecasting": "forecasting",
    "correlation": "correlation",
    "entity": "entity",
    "etiological": "etiological",
}


def fmt_float(value: Any, digits: int = 4) -> str:
    if value is None:
        return "N/A"
    if isinstance(value, float):
        return f"{value:.{digits}f}"
    return str(value)


def compact_idx_list(values: list[int]) -> str:
    if not values:
        return "[]"
    return "[" + ", ".join(str(v) for v in values) + "]"


def stats(values: list[float]) -> dict[str, Any]:
    if not values:
        return {"count": 0, "median": None, "mean": None, "min": None, "max": None}
    return {
        "count": len(values),
        "median": median(values),
        "mean": mean(values),
        "min": min(values),
        "max": max(values),
    }


def load_cases() -> list[dict]:
    cases: list[dict] = []
    for name in ["reasoning_numeric_fidelity_cases.json", "cross_node_numeric_reconstruction_cases.json"]:
        path = find_bad_cases.OUT_DIR / name
        if path.exists():
            cases.extend(json.loads(path.read_text(encoding="utf-8")))
    return cases


def mismatch_check(case: dict) -> dict:
    return case.get("top_reasoning_numeric_check") or case


def load_task_data() -> dict[str, list[dict]]:
    return {task: load_jsonl(ST_TEST / f"{task}_test.jsonl") for task in TASKS}


def load_generated_outputs(task: str) -> list[dict]:
    return json.loads(generated_path(task).read_text(encoding="utf-8"))


def load_official_metrics(task: str) -> dict:
    return json.loads(generated_path(task).parent.joinpath("evaluation_metrics.json").read_text(encoding="utf-8"))


def build_mismatch_summary(cases: list[dict], task_data: dict[str, list[dict]]) -> dict[str, dict]:
    by_task: dict[str, list[dict]] = {task: [] for task in TASKS}
    for case in cases:
        by_task[case["task_type"]].append(case)

    summary: dict[str, dict] = {}
    for task in TASKS:
        task_cases = by_task[task]
        idxs = sorted({int(case["idx"]) for case in task_cases})
        summary[task] = {
            "task": task,
            "mismatch_sample_count": len(idxs),
            "total_samples": len(task_data[task]),
            "mismatch_window_count": sum(
                len(case.get("reasoning_numeric_checks", [])) if case.get("reasoning_numeric_checks") else 1
                for case in task_cases
            ),
            "mismatch_indices": idxs,
            "note": "",
        }
    return summary


def build_extractable_summary(task_data: dict[str, list[dict]]) -> dict[str, dict]:
    summary: dict[str, dict] = {}
    for task in TASKS:
        outputs = load_generated_outputs(task)
        output_by_idx = {int(item["idx"]): item.get("response", "") for item in outputs}
        sample_ids: set[int] = set()
        window_count = 0
        mismatch_sample_ids: set[int] = set()
        mismatch_window_count = 0
        for idx, sample in enumerate(task_data[task]):
            response = output_by_idx.get(idx, "")
            all_checks = extract_numeric_reconstructions(sample, response, mismatch_only=False)
            mismatch_checks = [
                check for check in all_checks if check["max_abs_diff_between_stated_and_raw"] > 0.01
            ]
            if all_checks:
                sample_ids.add(idx)
                window_count += len(all_checks)
            if mismatch_checks:
                mismatch_sample_ids.add(idx)
                mismatch_window_count += len(mismatch_checks)
        summary[task] = {
            "extractable_sample_count": len(sample_ids),
            "extractable_window_count": window_count,
            "strict_mismatch_sample_count": len(mismatch_sample_ids),
            "strict_mismatch_window_count": mismatch_window_count,
            "extractable_indices": sorted(sample_ids),
        }
    return summary


def forecasting_group_metrics(task_data: list[dict], mismatch_indices: set[int]) -> dict[str, dict]:
    predictions = load_prediction_files(str(exp_dir("forecasting")))
    groups = {
        "all": set(range(len(task_data))),
        "mismatch": set(mismatch_indices),
        "other": set(range(len(task_data))) - set(mismatch_indices),
    }
    result: dict[str, dict] = {}
    for group, indices in groups.items():
        evaluated = 0
        missing_indices: list[int] = []
        mae_sum = 0.0
        mape_sum = 0.0
        mape_valid_count = 0
        for idx in sorted(indices):
            target_series = _parse_series(task_data[idx].get("output"))
            pred_text = predictions.get(idx)
            pred_series = _parse_series(pred_text) if pred_text is not None else []
            if not target_series or not pred_series:
                missing_indices.append(idx)
                continue
            if len(pred_series) < len(target_series):
                pred_series = pred_series + [pred_series[-1]] * (len(target_series) - len(pred_series))
            elif len(pred_series) > len(target_series):
                pred_series = pred_series[: len(target_series)]
            abs_errors = [abs(pred_series[i] - target_series[i]) for i in range(len(target_series))]
            mae_sum += sum(abs_errors) / len(abs_errors)
            percent_errors = [
                abs(pred_series[i] - target_series[i]) / abs(target_series[i])
                for i in range(len(target_series))
                if abs(target_series[i]) > 1e-8
            ]
            if percent_errors:
                mape_sum += sum(percent_errors) / len(percent_errors) * 100
                mape_valid_count += 1
            evaluated += 1
        result[group] = {
            "sample_count": len(indices),
            "evaluated_samples": evaluated,
            "missing_predictions": len(indices) - evaluated,
            "mae": mae_sum / evaluated if evaluated else None,
            "mape": mape_sum / mape_valid_count if mape_valid_count else None,
            "missing_indices": missing_indices,
        }
    return result


def choice_group_metrics(task: str, task_data: list[dict], mismatch_indices: set[int]) -> dict[str, dict]:
    predictions = load_prediction_files(str(exp_dir(task)))
    groups = {
        "all": set(range(len(task_data))),
        "mismatch": set(mismatch_indices),
        "other": set(range(len(task_data))) - set(mismatch_indices),
    }
    result: dict[str, dict] = {}
    for group, indices in groups.items():
        evaluated = 0
        correct = 0
        missing_indices_list: list[int] = []
        for idx in sorted(indices):
            pred = predictions.get(idx)
            if pred is None:
                missing_indices_list.append(idx)
                continue
            evaluated += 1
            if _normalize_choice(pred) == _normalize_choice(task_data[idx].get("output")):
                correct += 1
        result[group] = {
            "sample_count": len(indices),
            "evaluated_samples": evaluated,
            "missing_predictions": len(indices) - evaluated,
            "correct": correct,
            "accuracy": correct / evaluated if evaluated else None,
            "missing_indices": missing_indices_list,
        }
    return result


def build_metric_comparison(task_data: dict[str, list[dict]], mismatch_summary: dict[str, dict]) -> dict[str, dict]:
    metrics: dict[str, dict] = {}
    for task in TASKS:
        mismatch_indices = set(mismatch_summary[task]["mismatch_indices"])
        official = load_official_metrics(task)
        if task == "forecasting":
            groups = forecasting_group_metrics(task_data[task], mismatch_indices)
            mae_match = round(groups["all"]["mae"], 12) == round(official["mae"], 12)
            evaluated_match = groups["all"]["evaluated_samples"] == official["evaluated_samples"]
            if "mape" in official and groups["all"]["mape"] is not None:
                metrics_match = mae_match and round(groups["all"]["mape"], 12) == round(official["mape"], 12) and evaluated_match
            else:
                metrics_match = mae_match and evaluated_match
            validation = {
                "matches_existing_metrics_file": metrics_match,
                "note": "Group metrics are recomputed with the current repository parser; existing evaluation_metrics.json may have been produced by an earlier parser/run or omit MAPE.",
            }
        else:
            groups = choice_group_metrics(task, task_data[task], mismatch_indices)
            validation = {
                "matches_existing_metrics_file": (
                    round(groups["all"]["accuracy"], 12) == round(official["accuracy"], 12)
                    and groups["all"]["evaluated_samples"] == official["evaluated_samples"]
                ),
                "note": "Group metrics are recomputed with the current repository parser.",
            }
        metrics[task] = {"existing_metrics_file": official, "current_parser_validation": validation, "groups": groups}
    return metrics


def build_severity(cases: list[dict], task_data: dict[str, list[dict]]) -> dict[str, dict]:
    values: dict[str, dict[str, list[float]]] = {
        task: {"window_length": [], "window_ratio": [], "mean_abs_diff": [], "max_abs_diff": []}
        for task in TASKS
    }
    for case in cases:
        task = case["task_type"]
        sample = task_data[task][int(case["idx"])]
        checks = case.get("reasoning_numeric_checks") or [case]
        for check in checks:
            node = check["node"]
            raw_len = len(sample["timeseries"][node])
            win_len = len(check["raw_values"])
            values[task]["window_length"].append(float(win_len))
            values[task]["window_ratio"].append(win_len / raw_len if raw_len else 0.0)
            values[task]["mean_abs_diff"].append(check["mean_abs_diff_between_stated_and_raw"])
            values[task]["max_abs_diff"].append(check["max_abs_diff_between_stated_and_raw"])
    return {
        task: {
            metric: stats(series)
            for metric, series in metric_values.items()
        }
        for task, metric_values in values.items()
    }


def build_audit_cases(cases: list[dict]) -> dict[str, list[dict]]:
    by_task: dict[str, list[dict]] = defaultdict(list)
    for case in cases:
        by_task[case["task_type"]].append(case)
    audit: dict[str, list[dict]] = {}
    for task, task_cases in by_task.items():
        rows = []
        seen: set[int] = set()
        for case in task_cases:
            if int(case["idx"]) in seen:
                continue
            seen.add(int(case["idx"]))
            check = mismatch_check(case)
            rows.append(
                {
                    "idx": int(case["idx"]),
                    "data_file": case["data_file"],
                    "line_no": int(case["line_no"]),
                    "node": check["node"],
                    "window": check["stated_window"],
                    "alignment_basis": check.get("alignment_basis"),
                    "raw_values": check["raw_values"],
                    "model_stated_values": check["model_stated_values"],
                    "mean_abs_diff": check["mean_abs_diff_between_stated_and_raw"],
                    "max_abs_diff": check["max_abs_diff_between_stated_and_raw"],
                    "reasoning_line": check["reasoning_line"],
                }
            )
            if len(rows) >= 10:
                break
        audit[task] = rows
    return audit


def write_mismatch_markdown(summary: dict[str, dict], extractable: dict[str, dict]) -> None:
    rows = [
        "| 任务 | 对不上样本数 a/b | 对不上窗口数 | 可抽取复述样本数 | 对不上样本 idx 全列表 | 备注 |",
        "| --- | ---: | ---: | ---: | --- | --- |",
    ]
    for task in TASKS:
        item = summary[task]
        ext = extractable[task]
        if item["mismatch_sample_count"] == 0:
            note = "当前严格 node-window 数值列表抽取口径下未发现对不上；不等价于模型无此类问题"
        else:
            note = item["note"] or "严格 node-window 数值列表抽取，已尝试 0-based/1-based 保守对齐"
        rows.append(
            f"| {TASK_LABEL[task]} | {item['mismatch_sample_count']}/{item['total_samples']} | "
            f"{item['mismatch_window_count']} | {ext['extractable_sample_count']} | "
            f"{compact_idx_list(item['mismatch_indices'])} | {note} |"
        )
    (find_bad_cases.OUT_DIR / "task_level_reconstruction_mismatch.md").write_text("\n".join(rows) + "\n", encoding="utf-8")


def write_metric_markdown(metrics: dict[str, dict]) -> None:
    rows = [
        "| 任务 | 分组 | 样本数 | evaluated | missing | 指标 | 数值 |",
        "| --- | --- | ---: | ---: | ---: | --- | ---: |",
    ]
    for task in TASKS:
        groups = metrics[task]["groups"]
        if task == "forecasting":
            for group in ["all", "mismatch", "other"]:
                item = groups[group]
                rows.append(
                    f"| {task} | {group} | {item['sample_count']} | {item['evaluated_samples']} | "
                    f"{item['missing_predictions']} | MAE / MAPE | {fmt_float(item['mae'])} / {fmt_float(item['mape'])} |"
                )
        else:
            for group in ["all", "mismatch", "other"]:
                item = groups[group]
                rows.append(
                    f"| {task} | {group} | {item['sample_count']} | {item['evaluated_samples']} | "
                    f"{item['missing_predictions']} | accuracy | {fmt_float(item['accuracy'])} |"
                )
    (find_bad_cases.OUT_DIR / "task_level_metric_comparison.md").write_text("\n".join(rows) + "\n", encoding="utf-8")


def write_severity_markdown(severity: dict[str, dict]) -> None:
    rows = [
        "| 任务 | 指标 | count | median | mean | min | max |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for task in TASKS:
        for metric in ["window_length", "window_ratio", "mean_abs_diff", "max_abs_diff"]:
            item = severity[task][metric]
            rows.append(
                f"| {task} | {metric} | {item['count']} | {fmt_float(item['median'])} | "
                f"{fmt_float(item['mean'])} | {fmt_float(item['min'])} | {fmt_float(item['max'])} |"
            )
    (find_bad_cases.OUT_DIR / "reconstruction_error_severity_by_task.md").write_text("\n".join(rows) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=None, help="Repository root (default: auto-detect)")
    parser.add_argument(
        "--exp-suffix",
        default="",
        help='Exp dir suffix after sttest_full_{task}_6144, e.g. "_run2_official"',
    )
    parser.add_argument(
        "--out-subdir",
        default="",
        help="Subdirectory under mlp_encoder_focused_analysis/ for artifacts",
    )
    parser.add_argument(
        "--exp-layout",
        default="sttest6144",
        choices=["sttest6144", "bundled"],
        help="sttest6144 → exp/sttest_full_{task}_6144; bundled → exp_STReasoner-8B/reasoning_{task}-STReasoner-8B",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    configure_paths(
        root=Path(args.root) if args.root else None,
        exp_suffix=args.exp_suffix,
        out_subdir=args.out_subdir,
        exp_layout=args.exp_layout,
    )
    find_bad_cases.OUT_DIR.mkdir(parents=True, exist_ok=True)
    cases = load_cases()
    task_data = load_task_data()
    mismatch_summary = build_mismatch_summary(cases, task_data)
    extractable_summary = build_extractable_summary(task_data)
    metric_comparison = build_metric_comparison(task_data, mismatch_summary)
    severity = build_severity(cases, task_data)
    audit = build_audit_cases(cases)

    payloads = {
        "task_level_reconstruction_mismatch.json": {
            "definition": {
                "sample_count_a": "Unique sample idx with at least one strict node/window reconstruction mismatch.",
                "mismatch_threshold": "max_abs_diff_between_stated_and_raw > 0.01 after choosing the better of 0-based and 1-based alignment.",
            },
            "tasks": mismatch_summary,
            "extractable_direct_reconstruction": extractable_summary,
        },
        "task_level_metric_comparison.json": metric_comparison,
        "reconstruction_error_severity_by_task.json": severity,
        "manual_audit_top10_reconstruction_mismatch.json": audit,
    }
    for name, payload in payloads.items():
        (find_bad_cases.OUT_DIR / name).write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

    write_mismatch_markdown(mismatch_summary, extractable_summary)
    write_metric_markdown(metric_comparison)
    write_severity_markdown(severity)

    print(json.dumps(payloads["task_level_reconstruction_mismatch.json"]["tasks"], ensure_ascii=False, indent=2))
    print(find_bad_cases.OUT_DIR)


if __name__ == "__main__":
    main()
